// angular-h5/src/app/features/statistics/statistics.component.ts
/**
 * 数据统计页组件
 * 使用 Chart.js 展示任务完成率、趋势图和状态分布
 */

import { Component, inject, OnInit, AfterViewInit, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ElementRef, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { ApiService } from '../../core/services/api.service';
import { TopBarComponent } from '../../shared/components/top-bar/top-bar.component';
import { EmptyStateComponent } from '../../shared/components/empty-state/empty-state.component';
import type { ITodoTaskResponse, EApiTaskPriority } from '../../shared/models/api.model';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  BarController,
  LineElement,
  LineController,
  PointElement,
  ArcElement,
  PieController,
  DoughnutController,
  Title,
  Tooltip,
  Legend,
  Filler
} from 'chart.js';

// 注册 Chart.js 组件
ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  BarController,
  LineElement,
  LineController,
  PointElement,
  ArcElement,
  PieController,
  DoughnutController,
  Title,
  Tooltip,
  Legend,
  Filler
);

/** 图表类型 */
type EChartType = 'completion' | 'trend' | 'distribution';

/** Tab 选项 */
const TAB_OPTIONS = [
  { value: 'completion' as const, label: '完成率' },
  { value: 'trend' as const, label: '趋势图' },
  { value: 'distribution' as const, label: '状态分布' }
];

/** 图表颜色 */
const CHART_COLORS = {
  blue: 'rgb(59, 130, 246)',
  green: 'rgb(34, 197, 94)',
  amber: 'rgb(245, 158, 11)',
  red: 'rgb(239, 68, 68)',
  gray: 'rgb(156, 163, 175)'
};

@Component({
  selector: 'app-statistics',
  standalone: true,
  imports: [CommonModule, TopBarComponent, EmptyStateComponent],
  templateUrl: './statistics.component.html',
  styleUrl: './statistics.component.scss'
})
export class StatisticsComponent implements OnInit, AfterViewInit {
  private apiService = inject(ApiService);
  private router = inject(Router);

  /** 当前图表类型 */
  chartType: EChartType = 'completion';
  /** 任务列表 */
  tasks: ITodoTaskResponse[] = [];
  /** 加载状态 */
  loading = true;

  /** Tab 选项 */
  tabOptions = TAB_OPTIONS;

  /** 当前图表标题 */
  chartTitle = computed(() => {
    return TAB_OPTIONS.find(t => t.value === this.chartType)?.label || '';
  });

  /** 图表容器引用 */
  @ViewChild('chartCanvas', { static: false }) chartCanvas!: ElementRef<HTMLCanvasElement>;
  /** 图表实例 */
  private chartInstance: ChartJS | null = null;
  /** 视图已初始化标志 */
  private viewInitialized = false;

  ngOnInit(): void {
    this.fetchTasks();
  }

  /** 获取任务数据 */
  fetchTasks(): void {
    this.apiService.getTaskList().subscribe({
      next: (data) => {
        this.tasks = data;
        this.loading = false;
        // 数据加载完成后渲染图表
        if (this.viewInitialized && data.length > 0) {
          setTimeout(() => this.renderChart());
        }
      },
      error: (err) => {
        console.error('获取统计数据失败:', err);
        this.loading = false;
      }
    });
  }

  /** 切换图表类型 */
  onSetChartType(type: EChartType): void {
    this.chartType = type;
    this.renderChart();
  }

  /** 渲染图表 */
  renderChart(): void {
    if (!this.chartCanvas) return;

    // 销毁旧图表
    if (this.chartInstance) {
      this.chartInstance.destroy();
    }

    const ctx = this.chartCanvas.nativeElement.getContext('2d');
    if (!ctx) return;

    switch (this.chartType) {
      case 'completion':
        this.renderCompletionChart(ctx);
        break;
      case 'trend':
        this.renderTrendChart(ctx);
        break;
      case 'distribution':
        this.renderDistributionChart(ctx);
        break;
    }
  }

  /** 渲染完成率图表 */
  private renderCompletionChart(ctx: CanvasRenderingContext2D): void {
    const total = this.tasks.length;
    const completed = this.tasks.filter(t => t.status === 'COMPLETED').length;
    const overall = total > 0 ? Math.round((completed / total) * 100) : 0;

    // 按优先级统计
    const byPriority: Record<EApiTaskPriority, { total: number; completed: number; rate: number }> = {
      HIGH: { total: 0, completed: 0, rate: 0 },
      MEDIUM: { total: 0, completed: 0, rate: 0 },
      LOW: { total: 0, completed: 0, rate: 0 }
    };

    this.tasks.forEach(task => {
      byPriority[task.priority].total++;
      if (task.status === 'COMPLETED') {
        byPriority[task.priority].completed++;
      }
    });

    Object.keys(byPriority).forEach(key => {
      const p = byPriority[key as EApiTaskPriority];
      p.rate = p.total > 0 ? Math.round((p.completed / p.total) * 100) : 0;
    });

    this.chartInstance = new ChartJS(ctx, {
      type: 'bar',
      data: {
        labels: ['总体', '高优先级', '中优先级', '低优先级'],
        datasets: [{
          label: '完成率 (%)',
          data: [
            overall,
            byPriority.HIGH.rate,
            byPriority.MEDIUM.rate,
            byPriority.LOW.rate
          ],
          backgroundColor: [
            CHART_COLORS.blue,
            CHART_COLORS.red,
            CHART_COLORS.amber,
            CHART_COLORS.green
          ],
          borderRadius: 8
        }]
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: { display: false }
        },
        scales: {
          y: {
            beginAtZero: true,
            max: 100
          }
        }
      }
    });
  }

  /** 渲染趋势图 */
  private renderTrendChart(ctx: CanvasRenderingContext2D): void {
    const days: string[] = [];
    const created: number[] = [];
    const completed: number[] = [];

    for (let i = 6; i >= 0; i--) {
      const date = new Date();
      date.setDate(date.getDate() - i);
      const dateStr = date.toISOString().split('T')[0];
      days.push(`${date.getMonth() + 1}/${date.getDate()}`);

      const createdCount = this.tasks.filter(t => t.createdAt.startsWith(dateStr)).length;
      const completedCount = this.tasks.filter(t =>
        t.completedAt && t.completedAt.startsWith(dateStr)
      ).length;

      created.push(createdCount);
      completed.push(completedCount);
    }

    this.chartInstance = new ChartJS(ctx, {
      type: 'line',
      data: {
        labels: days,
        datasets: [
          {
            label: '新增任务',
            data: created,
            borderColor: CHART_COLORS.blue,
            backgroundColor: 'rgba(59, 130, 246, 0.2)',
            fill: true,
            tension: 0.3
          },
          {
            label: '完成任务',
            data: completed,
            borderColor: CHART_COLORS.green,
            backgroundColor: 'rgba(34, 197, 94, 0.2)',
            fill: true,
            tension: 0.3
          }
        ]
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            display: true,
            position: 'bottom'
          }
        },
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
  }

  /** 渲染状态分布图 */
  private renderDistributionChart(ctx: CanvasRenderingContext2D): void {
    const completed = this.tasks.filter(t => t.status === 'COMPLETED').length;
    const pending = this.tasks.filter(t => t.status === 'PENDING').length;

    this.chartInstance = new ChartJS(ctx, {
      type: 'pie',
      data: {
        labels: ['已完成', '未完成'],
        datasets: [{
          data: [completed, pending],
          backgroundColor: [CHART_COLORS.green, CHART_COLORS.gray],
          borderWidth: 0
        }]
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            display: true,
            position: 'bottom'
          }
        }
      }
    });
  }

  /** 获取统计概览数据 */
  getOverviewData() {
    return {
      total: this.tasks.length,
      completed: this.tasks.filter(t => t.status === 'COMPLETED').length,
      pending: this.tasks.filter(t => t.status === 'PENDING').length
    };
  }

  /** 返回上一页 */
  onBack(): void {
    this.router.navigate(['']);
  }

  /** ngAfterViewInit 生命周期 */
  ngAfterViewInit(): void {
    this.viewInitialized = true;
    // 如果已有数据，渲染图表
    if (this.tasks.length > 0) {
      setTimeout(() => this.renderChart());
    }
  }
}

<div class="statistics-page">
  <!-- 顶部导航栏 -->
  <app-top-bar
    title="数据统计"
    [showBack]="true"
    (back)="onBack()" />

  <!-- 主内容区 -->
  <main class="statistics-main">
    @if (loading) {
      <div class="loading-state">
        <span>加载中...</span>
      </div>
    } @else if (tasks.length === 0) {
      <app-empty-state type="statistics" text="暂无统计数据，添加任务后即可查看" />
    } @else {
      <!-- Tab 切换 -->
      <div class="chart-tabs">
        @for (option of tabOptions; track option.value) {
          <button
            class="chart-tab"
            [class.active]="chartType === option.value"
            (click)="onSetChartType(option.value)">
            {{ option.label }}
          </button>
        }
      </div>

      <!-- 统计概览 -->
      <div class="overview-grid">
        <div class="overview-card">
          <div class="overview-value overview-total">{{ getOverviewData().total }}</div>
          <div class="overview-label">总任务</div>
        </div>
        <div class="overview-card">
          <div class="overview-value overview-completed">{{ getOverviewData().completed }}</div>
          <div class="overview-label">已完成</div>
        </div>
        <div class="overview-card">
          <div class="overview-value overview-pending">{{ getOverviewData().pending }}</div>
          <div class="overview-label">未完成</div>
        </div>
      </div>

      <!-- 图表区域 -->
      <div class="chart-card">
        <h3 class="chart-title">
          {{ chartTitle() }}
        </h3>
        <div class="chart-container">
          <canvas #chartCanvas></canvas>
        </div>
      </div>

      <!-- 统计说明 -->
      <div class="info-card">
        <h3 class="info-title">统计说明</h3>
        @if (chartType === 'completion') {
          <p class="info-text">
            展示所有任务的总体完成率以及按优先级分类的完成率。
            完成率 = 已完成任务数 / 总任务数 × 100%
          </p>
        } @else if (chartType === 'trend') {
          <p class="info-text">
            展示近 7 天每日新增任务数和完成任务数的趋势变化。
            蓝色区域表示新增任务，绿色区域表示完成任务。
          </p>
        } @else {
          <p class="info-text">
            展示当前所有任务中已完成和未完成的数量占比。
          </p>
        }
      </div>
    }
  </main>
</div>

// client-react-plugin-glm/src/pages/Statistics.tsx
/**
 * 数据统计页面
 */
import React, { useState, useMemo } from 'react'
import Header from '@/components/Common/Header'
import EmptyState from '@/components/Common/EmptyState'
import { useTodoStore } from '@/store/todoStore'
import { formatDate, getRecent7Days } from '@/utils/date'
import { Chart as ChartJS, CategoryScale, LinearScale, BarElement, LineElement, PointElement, ArcElement, Title, Tooltip, Legend } from 'chart.js'
import { Bar, Line, Pie } from 'react-chartjs-2'
import clsx from 'classnames'

// 注册Chart.js组件
ChartJS.register(CategoryScale, LinearScale, BarElement, LineElement, PointElement, ArcElement, Title, Tooltip, Legend)

type TabType = 'completion-rate' | 'trend' | 'distribution'

const Statistics: React.FC = () => {
  const { todos } = useTodoStore()
  const [activeTab, setActiveTab] = useState<TabType>('completion-rate')
  
  // 获取近7天日期
  const recent7Days = useMemo(() => getRecent7Days(), [])
  
  // 计算统计数据
  const statistics = useMemo(() => {
    // 基础统计
    const total = todos.length
    const completed = todos.filter(todo => todo.status === 'completed').length
    const pending = total - completed
    
    // 计算逾期任务
    const now = new Date()
    const overdue = todos.filter(todo => 
      todo.status === 'pending' && 
      todo.dueDate && 
      new Date(todo.dueDate) < now
    ).length
    
    // 计算完成率
    const completionRate = total > 0 ? Math.round((completed / total) * 100) : 0
    
    // 按优先级统计
    const byPriority = {
      high: {
        total: todos.filter(todo => todo.priority === 'high').length,
        completed: todos.filter(todo => todo.priority === 'high' && todo.status === 'completed').length,
      },
      medium: {
        total: todos.filter(todo => todo.priority === 'medium').length,
        completed: todos.filter(todo => todo.priority === 'medium' && todo.status === 'completed').length,
      },
      low: {
        total: todos.filter(todo => todo.priority === 'low').length,
        completed: todos.filter(todo => todo.priority === 'low' && todo.status === 'completed').length,
      },
    }
    
    // 每日趋势数据
    const dailyTrend = recent7Days.map(day => {
      const dayDate = day.date
      const created = todos.filter(todo => formatDate(todo.createdAt) === dayDate).length
      const completed = todos.filter(todo => 
        todo.completedAt && formatDate(todo.completedAt) === dayDate
      ).length
      
      return {
        date: dayDate,
        label: day.label,
        created,
        completed,
      }
    })
    
    return {
      total,
      completed,
      pending,
      overdue,
      completionRate,
      byPriority,
      dailyTrend,
    }
  }, [todos, recent7Days])
  
  // 选项卡数据
  const tabs = [
    { key: 'completion-rate' as TabType, label: '完成率' },
    { key: 'trend' as TabType, label: '趋势图' },
    { key: 'distribution' as TabType, label: '状态分布' },
  ]
  
  // 完成率图表数据
  const completionRateChartData = {
    labels: ['高优先级', '中优先级', '低优先级', '总体'],
    datasets: [
      {
        label: '完成率 (%)',
        data: [
          statistics.byPriority.high.total > 0 
            ? Math.round((statistics.byPriority.high.completed / statistics.byPriority.high.total) * 100) 
            : 0,
          statistics.byPriority.medium.total > 0 
            ? Math.round((statistics.byPriority.medium.completed / statistics.byPriority.medium.total) * 100) 
            : 0,
          statistics.byPriority.low.total > 0 
            ? Math.round((statistics.byPriority.low.completed / statistics.byPriority.low.total) * 100) 
            : 0,
          statistics.completionRate,
        ],
        backgroundColor: [
          'rgba(239, 68, 68, 0.5)',
          'rgba(245, 158, 11, 0.5)',
          'rgba(34, 197, 94, 0.5)',
          'rgba(59, 130, 246, 0.5)',
        ],
        borderColor: [
          'rgb(239, 68, 68)',
          'rgb(245, 158, 11)',
          'rgb(34, 197, 94)',
          'rgb(59, 130, 246)',
        ],
        borderWidth: 1,
      },
    ],
  }
  
  // 趋势图表数据
  const trendChartData = {
    labels: statistics.dailyTrend.map(item => item.label),
    datasets: [
      {
        label: '新增任务',
        data: statistics.dailyTrend.map(item => item.created),
        borderColor: 'rgb(59, 130, 246)',
        backgroundColor: 'rgba(59, 130, 246, 0.1)',
        tension: 0.4,
        fill: true,
      },
      {
        label: '完成任务',
        data: statistics.dailyTrend.map(item => item.completed),
        borderColor: 'rgb(34, 197, 94)',
        backgroundColor: 'rgba(34, 197, 94, 0.1)',
        tension: 0.4,
        fill: true,
      },
    ],
  }
  
  // 状态分布图表数据
  const distributionChartData = {
    labels: ['未完成', '已完成', '已逾期'],
    datasets: [
      {
        data: [statistics.pending, statistics.completed, statistics.overdue],
        backgroundColor: [
          'rgba(245, 158, 11, 0.5)',
          'rgba(34, 197, 94, 0.5)',
          'rgba(239, 68, 68, 0.5)',
        ],
        borderColor: [
          'rgb(245, 158, 11)',
          'rgb(34, 197, 94)',
          'rgb(239, 68, 68)',
        ],
        borderWidth: 1,
      },
    ],
  }
  
  // 图表选项
  const chartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: 'top' as const,
      },
    },
    scales: activeTab !== 'distribution' ? {
      y: {
        beginAtZero: true,
        ticks: {
          stepSize: activeTab === 'completion-rate' ? 20 : 1,
        },
      },
    } : undefined,
  }
  
  // 没有数据时的提示
  if (statistics.total === 0) {
    return (
      <div className="h-full flex flex-col bg-gray-50">
        <Header title="数据统计" />
        <EmptyState
          icon="fas fa-chart-pie"
          title="暂无统计数据"
          description="添加任务后即可查看"
        />
      </div>
    )
  }
  
  return (
    <div className="h-full flex flex-col bg-gray-50">
      <Header title="数据统计" />
      
      {/* 选项卡 */}
      <div className="bg-white border-b border-gray-200">
        <div className="flex">
          {tabs.map(tab => (
            <button
              key={tab.key}
              className={clsx(
                'flex-1 py-3 text-sm font-medium',
                activeTab === tab.key
                  ? 'text-primary border-b-2 border-primary'
                  : 'text-gray-500'
              )}
              onClick={() => setActiveTab(tab.key)}
            >
              {tab.label}
            </button>
          ))}
        </div>
      </div>
      
      {/* 图表区域 */}
      <div className="flex-1 overflow-y-auto p-4">
        {/* 完成率选项卡 */}
        {activeTab === 'completion-rate' && (
          <div className="bg-white rounded-lg p-4">
            <h3 className="text-base font-medium mb-4">近7天任务完成率</h3>
            <div className="h-64">
              <Bar data={completionRateChartData} options={chartOptions} />
            </div>
            <div className="mt-4 grid grid-cols-2 gap-4">
              <div className="bg-gray-50 rounded-lg p-3 text-center">
                <div className="text-2xl font-bold text-primary">{statistics.completionRate}%</div>
                <div className="text-xs text-gray-500 mt-1">总体完成率</div>
              </div>
              <div className="bg-gray-50 rounded-lg p-3 text-center">
                <div className="text-2xl font-bold text-green-500">{statistics.completed}</div>
                <div className="text-xs text-gray-500 mt-1">已完成任务</div>
              </div>
            </div>
          </div>
        )}
        
        {/* 趋势图选项卡 */}
        {activeTab === 'trend' && (
          <div className="bg-white rounded-lg p-4">
            <h3 className="text-base font-medium mb-4">近7天任务趋势</h3>
            <div className="h-64">
              <Line data={trendChartData} options={chartOptions} />
            </div>
            <div className="mt-4 grid grid-cols-2 gap-4">
              <div className="bg-gray-50 rounded-lg p-3 text-center">
                <div className="text-2xl font-bold text-blue-500">
                  {statistics.dailyTrend.reduce((sum, item) => sum + item.created, 0)}
                </div>
                <div className="text-xs text-gray-500 mt-1">近7天新增</div>
              </div>
              <div className="bg-gray-50 rounded-lg p-3 text-center">
                <div className="text-2xl font-bold text-green-500">
                  {statistics.dailyTrend.reduce((sum, item) => sum + item.completed, 0)}
                </div>
                <div className="text-xs text-gray-500 mt-1">近7天完成</div>
              </div>
            </div>
          </div>
        )}
        
        {/* 状态分布选项卡 */}
        {activeTab === 'distribution' && (
          <div className="bg-white rounded-lg p-4">
            <h3 className="text-base font-medium mb-4">任务状态分布</h3>
            <div className="h-64">
              <Pie data={distributionChartData} options={chartOptions} />
            </div>
            <div className="mt-4 space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center">
                  <div className="w-3 h-3 bg-yellow-500 rounded-full mr-2"></div>
                  <span className="text-sm">未完成</span>
                </div>
                <span className="text-sm font-medium">{statistics.pending}</span>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center">
                  <div className="w-3 h-3 bg-green-500 rounded-full mr-2"></div>
                  <span className="text-sm">已完成</span>
                </div>
                <span className="text-sm font-medium">{statistics.completed}</span>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center">
                  <div className="w-3 h-3 bg-red-500 rounded-full mr-2"></div>
                  <span className="text-sm">已逾期</span>
                </div>
                <span className="text-sm font-medium">{statistics.overdue}</span>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

export default Statistics
